from ._alignment import (
    best_first_simulated_integration,
    irregular_intervals,
    match_simulated_integration_pair,
    overlap_window_hours,
)
from ._bootstrap import bca_interval, cohens_h, patient_clustered_bootstrap
from ._calibration import (
    apply_platt,
    apply_temperature,
    brier_score,
    calibration_slope,
    expected_calibration_error,
    fit_platt,
    fit_temperature,
    reliability_bins,
)
from ._clinical_panel import (
    CLINICAL_FEATURE_NAMES,
    DRUG_CLASS_FLAGS,
    LABORATORY_FEATURES,
    PROCEDURE_FLAGS,
    VITAL_SIGN_FEATURES,
    aggregate_to_six_hour_panel,
    feature_index_lookup,
    impute_clinical_panel,
    six_hour_bin_edges,
)
from ._cohort_split import (
    assert_split_disjoint,
    stratified_patient_disjoint_split,
)
from ._composite_pe import (
    composite_positional_encoding,
    continuous_time_sinusoidal_encoding,
    disease_phase_embedding_table,
    lookup_phase_embedding,
    treatment_phase_embedding_table,
)
from ._decision_curve import (
    decision_curve,
    number_needed_to_screen,
    number_needed_to_treat,
)
from ._delong import auroc, bonferroni_adjust, paired_delong
from ._diversity import (
    alpha_diversity_panel,
    observed_richness,
    pielou_evenness,
    shannon_entropy,
    taxon_ratio,
)
from ._focal_loss import focal_cross_entropy, focal_cross_entropy_gradient
from ._harmonise import (
    composition_aware_zscore,
    harmonise_across_centres,
    per_centre_platt_correction,
)
from ._risk_tiers import (
    classify_risk_tier,
    lead_time_threshold_crossing,
    vectorised_risk_tier,
)
from ._taxonomy import (
    counts_to_relative_abundance,
    filter_low_read_samples,
    restrict_to_taxa,
    rollup_to_genus,
    taxon_relative_abundance,
)
try:
    from ._torch_pe import (
        TorchCompositePositionalEncoding,
        torch_continuous_time_encoding,
    )
    from ._temporal_microbiome_encoder import TemporalMicrobiomeEncoder
    from ._clinical_feature_fusion import (
        BidirectionalCrossAttention,
        ClinicalEncoder,
        ClinicalFeatureFusion,
        FusionOutput,
    )
    from ._risk_score_generator import (
        AttentionWeightedTemporalPooling,
        RealTimeRiskScoreGenerator,
        RiskScoreOutput,
    )
    from ._mrs_network import (
        MicrobiomeRiskScoreNetwork,
        MicrobiomeRiskScoreOutput,
    )

    _NEURAL_NAMES = [
        "AttentionWeightedTemporalPooling",
        "BidirectionalCrossAttention",
        "ClinicalEncoder",
        "ClinicalFeatureFusion",
        "FusionOutput",
        "MicrobiomeRiskScoreNetwork",
        "MicrobiomeRiskScoreOutput",
        "RealTimeRiskScoreGenerator",
        "RiskScoreOutput",
        "TemporalMicrobiomeEncoder",
        "TorchCompositePositionalEncoding",
        "torch_continuous_time_encoding",
    ]
except ImportError:
    _NEURAL_NAMES = []


from ._types import (
    AbundanceTable,
    BONFERRONI_BASELINE_COUNT,
    BootstrapResult,
    CLINICAL_PANEL_DIMENSION,
    CalibrationConvergenceError,
    CalibrationFit,
    CohortLeakageError,
    CohortSplit,
    DEFAULT_BATCH_SIZE,
    DEFAULT_LEARNING_RATE,
    DEFAULT_MAX_EPOCHS,
    DEFAULT_PATIENCE_EPOCHS,
    DEFAULT_WEIGHT_DECAY,
    DISEASE_PHASE_STATES,
    DROPOUT_PROBABILITY,
    DecisionCurve,
    DeLongResult,
    DiseasePhase,
    EmptyAbundanceError,
    FOCAL_ALPHA,
    FOCAL_GAMMA,
    HIDDEN_DIMENSION,
    IncompatibleScoreVectorsError,
    InsufficientReadsError,
    MICROBIOME_BIN_HOURS,
    MICROBIOME_PANEL_DIMENSION,
    MINIMUM_READS_PER_SAMPLE,
    MatchedPair,
    PAPER_RANDOM_SEEDS,
    PlattFit,
    RISK_TIER_HIGH_CEILING,
    RISK_TIER_LOW_CEILING,
    RISK_TIER_MODERATE_CEILING,
    ReliabilityBin,
    RiskScorer,
    RiskTier,
    SIMULATED_INTEGRATION_MINIMUM_OVERLAP_HOURS,
    SIMULATED_INTEGRATION_MINIMUM_TIMEPOINTS,
    SIMULATED_INTEGRATION_SOFA_TOLERANCE,
    SPECIES_RESOLVED_GENERA,
    TEMPORAL_WINDOW_HOURS,
    TRANSFORMER_LAYERS,
    TREATMENT_PHASE_STATES,
    TreatmentModality,
)


__all__ = [
    "AbundanceTable",
    "BONFERRONI_BASELINE_COUNT",
    "BootstrapResult",
    "CLINICAL_FEATURE_NAMES",
    "CLINICAL_PANEL_DIMENSION",
    "CalibrationConvergenceError",
    "CalibrationFit",
    "CohortLeakageError",
    "CohortSplit",
    "DEFAULT_BATCH_SIZE",
    "DEFAULT_LEARNING_RATE",
    "DEFAULT_MAX_EPOCHS",
    "DEFAULT_PATIENCE_EPOCHS",
    "DEFAULT_WEIGHT_DECAY",
    "DISEASE_PHASE_STATES",
    "DROPOUT_PROBABILITY",
    "DRUG_CLASS_FLAGS",
    "DecisionCurve",
    "DeLongResult",
    "DiseasePhase",
    "EmptyAbundanceError",
    "FOCAL_ALPHA",
    "FOCAL_GAMMA",
    "HIDDEN_DIMENSION",
    "IncompatibleScoreVectorsError",
    "InsufficientReadsError",
    "LABORATORY_FEATURES",
    "MICROBIOME_BIN_HOURS",
    "MICROBIOME_PANEL_DIMENSION",
    "MINIMUM_READS_PER_SAMPLE",
    "MatchedPair",
    "PAPER_RANDOM_SEEDS",
    "PROCEDURE_FLAGS",
    "PlattFit",
    "RISK_TIER_HIGH_CEILING",
    "RISK_TIER_LOW_CEILING",
    "RISK_TIER_MODERATE_CEILING",
    "ReliabilityBin",
    "RiskScorer",
    "RiskTier",
    "SIMULATED_INTEGRATION_MINIMUM_OVERLAP_HOURS",
    "SIMULATED_INTEGRATION_MINIMUM_TIMEPOINTS",
    "SIMULATED_INTEGRATION_SOFA_TOLERANCE",
    "SPECIES_RESOLVED_GENERA",
    "TEMPORAL_WINDOW_HOURS",
    "TRANSFORMER_LAYERS",
    "TREATMENT_PHASE_STATES",
    "TreatmentModality",
    "VITAL_SIGN_FEATURES",
    "aggregate_to_six_hour_panel",
    "alpha_diversity_panel",
    "apply_platt",
    "apply_temperature",
    "assert_split_disjoint",
    "auroc",
    "bca_interval",
    "best_first_simulated_integration",
    "bonferroni_adjust",
    "brier_score",
    "calibration_slope",
    "classify_risk_tier",
    "cohens_h",
    "composite_positional_encoding",
    "composition_aware_zscore",
    "continuous_time_sinusoidal_encoding",
    "counts_to_relative_abundance",
    "decision_curve",
    "disease_phase_embedding_table",
    "expected_calibration_error",
    "feature_index_lookup",
    "filter_low_read_samples",
    "fit_platt",
    "fit_temperature",
    "focal_cross_entropy",
    "focal_cross_entropy_gradient",
    "harmonise_across_centres",
    "impute_clinical_panel",
    "irregular_intervals",
    "lead_time_threshold_crossing",
    "lookup_phase_embedding",
    "match_simulated_integration_pair",
    "number_needed_to_screen",
    "number_needed_to_treat",
    "observed_richness",
    "overlap_window_hours",
    "paired_delong",
    "patient_clustered_bootstrap",
    "per_centre_platt_correction",
    "pielou_evenness",
    "reliability_bins",
    "restrict_to_taxa",
    "rollup_to_genus",
    "shannon_entropy",
    "six_hour_bin_edges",
    "stratified_patient_disjoint_split",
    "taxon_ratio",
    "taxon_relative_abundance",
    "treatment_phase_embedding_table",
    "vectorised_risk_tier",
] + _NEURAL_NAMES
